### ISSUE TITLE
Link to the paper in motif recognition docs

### ISSUE THREAD

**Issue by felixcremer** [johncwok/CategoricalTimeSeries.jl#10]
It would be good to link to the JEREMY BUHLER and MARTIN TOMPA's paper "Finding Motifs Using Random Projections" paper that is mentioned in the motif docs.

Part of the review for JOSS https://github.com/openjournals/joss-reviews/issues/3733

**Comment by CNelias** [comment]
Done! I also added a link to the Spectral envelope paper as well as the categorical time-series analysis from Christian Weiss.
