### ISSUE TITLE
do you similar project in python ?

### ISSUE THREAD

**Issue by Sandy4321** [johncwok/CategoricalTimeSeries.jl#14]
great code 
but do you similar project in python ?

**Comment by CNelias** [comment]
Hi, 
I personally don't, but some of the methods have been implemented in python by others (e.g. the ```information bottleneck```, and ```motif recognition``` via the matrix profile). 
For the functions of the section ```spectral properties``` and ```correlation analysis``` of the package, I am not aware of any alternative unfortunately.

**Comment by Sandy4321** [comment]
great 
thanks for sharing

then do you links to python code for mentioned by you 
 1
information bottleneck
2
motif recognition

**Comment by Sandy4321** [comment]
for example as you mentioned in
https://categoricaltimeseriesjl.readthedocs.io/en/latest/Data_clustering/
The present implementation is adapted from DJ Strouse's paper https://arxiv.org/abs/1604.00268 and his python implementation
but how to find this python code ?
there is no link to code in 
https://arxiv.org/pdf/1604.00268.pdf

**Comment by Sandy4321** [comment]
is it
https://github.com/djstrouse/information-bottleneck
??

**Comment by CNelias** [comment]
Yes that's it. 
For motifs recognition, a good Python implementation of the matrix profile can be found [here](https://github.com/matrix-profile-foundation/matrixprofile), they also have a good [documentation](https://matrixprofile.docs.matrixprofile.org/).
