### ISSUE TITLE
Clarify whether this is a regroup of multiple modules

### ISSUE THREAD

**Issue by felixcremer** [johncwok/CategoricalTimeSeries.jl#3]
In the README you state, that this is regroup of multiple other modules.
Apparently you integrated the code of these modules into this main module and removed the dependency.
Is this correct?
 Then you should remove the sentence from the README.

**Comment by CNelias** [comment]
You are correct. My original plan was to do it so, but version numbering on the different packages caused so many issues upon registration that I decided to put everything in the main repo. 
I made changes to the README, and linked everything to the documentation.
