### ISSUE TITLE
Example in Correlation doc mixes Cohen_coefficient and cramer_coefficient

### ISSUE THREAD

**Issue by felixcremer** [johncwok/CategoricalTimeSeries.jl#4]
In the example of the correlation functions you use cohen_coefficient for the coefficient computation and then use cramer_coefficient in the bootstrap function.
I think, that this should be the same function.

**Comment by CNelias** [comment]
I fixed the label so that it matches the actual figure, and included it the doc.
The documentation hasn't updated yet (```readthedocs``` always takes a bit of time), but I guess changes will appear soon.
